name: Docker CI Pipeline

on:
    push:
        branches: [main]

jobs:
    docker-build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Extractg image metadata
              id: meta
              run: |
                echo "image_tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

            - name: Build Docker image
              run: |
                docker build \
                  -f docker/Dockerfile \
                  -t ${{ secrets.DOCKER_USERNAME }}/node-devops-demo:${{ steps.meta.outputs.image_tag }} \
                  -t ${{ secrets.DOCKER_USERNAME }}/node-devops-demo:latest \
                  .

            - name: Push Docker image
              run: |
                docker push ${{ secrets.DOCKER_USERNAME }}/node-devops-demo:${{ steps.meta.outputs.image_tag }}
                docker push ${{ secrets.DOCKER_USERNAME }}/node-devops-demo:latest